version: "3.3"

services:
  ###############################################
  ####              EXAMPLE                 #####
  ###############################################
  EXAMPLE:
    image: EXAMPLE/EXAMPLE
    container_name: EXAMPLE
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"                                                  #<== Enable traefik
      - "traefik.http.routers.EXAMPLE-secured.rule=HOST(`EXAMPLE.${DOMAIN}`)"  #<== Set domain
      - "traefik.http.routers.EXAMPLE-secured.entrypoints=websecure"           #<== Set entry point for HTTPS
      - "traefik.http.routers.EXAMPLE-secured.tls.certresolver=mytlschallenge" #<== Set certsresolvers for https
      - "traefik.http.routers.EXAMPLE-secured.middlewares=authelia"            #<== Add Authelia middlewares to protect login
      - "traefik.http.routers.EXAMPLE-secured.service=EXAMPLE-service"         #<== Set service
      - "traefik.http.services.EXAMPLE-service.loadbalancer.server.port=80"    #<== Set target port on container

networks:
  proxy:
    external: true