services:
    sharelatex:
        restart: always
        # Server Pro users:
        # image: quay.io/sharelatex/sharelatex-pro
        # image: sharelatex/sharelatex
        build: ./build/latex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        links:
            - mongo
            - redis
        # ports:
        #   - 4555:80
        expose:
            - 80
        volumes:
            - ./data/sharelatex:/var/lib/overleaf
            ########################################################################
            ####  Server Pro: Un-comment the following line to mount the docker ####
            ####             socket, required for Sibling Containers to work    ####
            ########################################################################
            # - /var/run/docker.sock:/var/run/docker.sock
        environment:
            OVERLEAF_APP_NAME: Overleaf Workspace # change to custom name

            OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex?replicaSet=rs0

            # Same property, unfortunately with different names in
            # different locations
            OVERLEAF_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: "url,project_file"

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: "true"

            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: "true"

            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

            OVERLEAF_EMAIL_FROM_ADDRESS: "postmaster@test.com" # change email

        networks:
            - proxy
            - sharelatex-backend
        labels:
            - "traefik.enable=true" #<== Enable traefik
            - "traefik.http.routers.sharelatex-secured.rule=Host(`latex.${DOMAIN}`)" #<== Set domain
            - "traefik.http.routers.sharelatex-secured.entrypoints=websecure" #<== Set entry point for HTTPS
            - "traefik.http.routers.sharelatex-secured.tls.certresolver=mytlschallenge" #<== Set certsresolvers for https
            - "traefik.http.routers.sharelatex-secured.middlewares=authelia" #<== Add Authelia middlewares to protect login
            - "traefik.http.routers.sharelatex-secured.service=sharelatex-service" #<== Set service
            - "traefik.http.services.sharelatex-service.loadbalancer.server.port=80" #<== Set target port on container

    mongo:
        restart: always
        # image: mongo:5.0
        build: ./build/mongo
        container_name: mongo
        command: --replSet rs0
        expose:
            - 27017
        volumes:
            - ./data/mongo:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - sharelatex-backend


    redis:
        restart: always
        image: redis:6.2
        container_name: redis
        expose:
            - 6379
        volumes:
            - ./data/redis:/data
        networks:
            - sharelatex-backend

networks:
    proxy:
        external: true
    sharelatex-backend:
        name: sharelatex-backend
        driver: bridge
