version: "3.3"

services:
  ###############################################
  ####              pastebin                #####
  ###############################################
  pastebin:
    image: mkodockx/docker-pastebin
    container_name: pastebin
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"                                                   #<== Enable traefik
      - "traefik.http.routers.pastebin-secured.rule=Host(`code.${DOMAIN}`)"     #<== Set domain
      - "traefik.http.routers.pastebin-secured.entrypoints=websecure"           #<== Set entry point for HTTPS
      - "traefik.http.routers.pastebin-secured.tls.certresolver=mytlschallenge" #<== Set certsresolvers for https
      - "traefik.http.routers.pastebin-secured.middlewares=authelia"            #<== Add Authelia middlewares to protect login
      - "traefik.http.routers.pastebin-secured.service=pastebin-service"        #<== Set service
      - "traefik.http.services.pastebin-service.loadbalancer.server.port=80"    #<== Set target port on container

networks:
  proxy:
    external: true