services:
  ###############################################
  ####              portainer                 #####
  ###############################################
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/Portainer/data:/data
    #ports:
    #  - "9000:9000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"                                                  #<== Enable traefik
      - "traefik.http.routers.portainer-secured.rule=Host(`portainer.${DOMAIN}`)"  #<== Set domain
      - "traefik.http.routers.portainer-secured.entrypoints=websecure"           #<== Set entry point for HTTPS
      - "traefik.http.routers.portainer-secured.tls.certresolver=mytlschallenge" #<== Set certsresolvers for https
      - "traefik.http.routers.portainer-secured.middlewares=authelia"            #<== Add Authelia middlewares to protect login
      - "traefik.http.routers.portainer-secured.service=portainer-service"         #<== Set service
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"    #<== Set target port on container

networks:
  proxy:
    external: true