version: "3.3"

services:
  ###############################################
  ####              uptime-kuma                 #####
  ###############################################
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data/:/app/data
    security_opt:
      - no-new-privileges
    networks:
      - proxy
    labels:
      - "traefik.enable=true"                                                       #<== Enable traefik
      - "traefik.http.routers.uptime-kuma-secured.rule=Host(`status.${DOMAIN}`)"    #<== Set domain
      - "traefik.http.routers.uptime-kuma-secured.entrypoints=websecure"            #<== Set entry point for HTTPS
      - "traefik.http.routers.uptime-kuma-secured.tls.certresolver=mytlschallenge"  #<== Set certsresolvers for https
      - "traefik.http.routers.uptime-kuma-secured.middlewares=authelia"             #<== Add Authelia middlewares to protect login
      - "traefik.http.routers.uptime-kuma-secured.service=uptime-kuma-service"      #<== Set service
      - "traefik.http.services.uptime-kuma-service.loadbalancer.server.port=3001"     #<== Set target port on container

networks:
  proxy:
    external: true