version: "3.3"

services:
  ###############################################
  ####               plantuml               #####
  ###############################################
  plantuml:
    image: plantuml/plantuml-server:tomcat # Or plantuml/plantuml-server:jetty
    container_name: plantuml
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"                                                    #<== Enable traefik
      - "traefik.http.routers.plantuml-secured.rule=Host(`plantuml.${DOMAIN}`)"  #<== Set domain
      - "traefik.http.routers.plantuml-secured.entrypoints=websecure"            #<== Set entry point for HTTPS
      - "traefik.http.routers.plantuml-secured.tls.certresolver=mytlschallenge"  #<== Set certsresolvers for https
      - "traefik.http.routers.plantuml-secured.middlewares=authelia"             #<== Add Authelia middlewares to protect login
      - "traefik.http.routers.plantuml-secured.service=plantuml-service"         #<== Set service
      - "traefik.http.services.plantuml-service.loadbalancer.server.port=8080"   #<== Set target port on container

networks:
  proxy:
    external: true