version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    #ports:
    #  - '80:3001'
    volumes:
      - /:/mnt/host:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"                                                       #<== Enable traefik
      - "traefik.http.routers.dash-dot-secured.rule=Host(`dash.${DOMAIN}`)"    #<== Set domain
      - "traefik.http.routers.dash-dot-secured.entrypoints=websecure"            #<== Set entry point for HTTPS
      - "traefik.http.routers.dash-dot-secured.tls.certresolver=mytlschallenge"  #<== Set certsresolvers for https
      - "traefik.http.routers.dash-dot-secured.middlewares=authelia"             #<== Add Authelia middlewares to protect login
      - "traefik.http.routers.dash-dot-secured.service=dash-dot-service"      #<== Set service
      - "traefik.http.services.dash-dot-service.loadbalancer.server.port=3001"     #<== Set target port on container

networks:
  proxy:
    external: true